In [42]:
#importando biblioteca
import pandas as pd

In [43]:
#informando o temanha de cada campo
width = [4,1,2,2,2,9,7,2,2,1,1,1,15,15,9,3,2,2,2,1,2,2,4,3,1,1,1,1,2,2,1,1,1,2,1,1,1,2,2,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,1,4,1,1,5,1,1,1,1,1,1,2,1,1,2,2,1,1,1,1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8,1,1,8,1,1,1,1,1,8,1,1,8,3,3,1,2,2,2,4,1,1,5,1,1,1,1,1,1,1,1,8,1,1,8,1,1,1,1,1,8,1,1,8,3,3,1,1,1,1,8,1,1,8,1,1,1,1,1,1,8,1,1,8,3,3,1,1,1,1,1,2,1,1,1,2,1,2,1,2,2,2,1,1,1,1,2,2,1,1,2,1,1,1,1,1,1,1,1,1,2,2,2,1,1,1,1,8,8,1,8,8,1,1,3,3,3,3,3,1,1,
]

In [44]:
#importando o arquico em um DataFrame
PNADc = pd.read_fwf('PNADC_012020.txt',widths = width, header = None,dtype= str)

In [45]:
#mostrando os 5 primeiros
PNADc.head()

,0,1,2,3,4,5,6,7,8,9,...,207,208,209,210,211,212,213,214,215,216
0,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,00001500,.,NaN,040,.,.,.,040,3,3
1,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,NaN,.,NaN,.,.,.,.,.,NaN,NaN
2,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,NaN,.,2,.,.,.,.,.,NaN,NaN
3,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,NaN,.,NaN,.,.,.,.,.,NaN,NaN
4,2020,1,11,11,NaN,110000016,1110011,03,07,5,...,NaN,.,4,.,.,.,.,.,NaN,NaN

In [46]:
PNADc.count()

0      487937
1      487937
2      487937
3      112619
4      151121
        ...
212    487937
213    487937
214    487937
215    203823
216    203823
Length: 217, dtype: int64

In [47]:
#informando o nome das colunas
PNADc.columns =["Ano","Trimestre","UF","Capital","RM_RIDE","UPA","Estrato","V1008","V1014","V1016","V1022","V1023","V1027","V1028","V1029","posest","V2001","V2003","V2005","V2007","V2008","V20081","V20082","V2009","V2010","V3001","V3002","V3002A","V3003","V3003A","V3004","V3005","V3005A","V3006","V3006A","V3007","V3008","V3009","V3009A","V3010","V3011","V3011A","V3012","V3013","V3013A","V3013B","V3014","V4001","V4002","V4003","V4004","V4005","V4006","V4006A","V4007","V4008","V40081","V40082","V40083","V4009","V4010","V4012","V40121","V4013","V40132","V40132A","V4014","V4015","V40151","V401511","V401512","V4016","V40161","V40162","V40163","V4017","V40171","V401711","V4018","V40181","V40182","V40183","V4019","V4020","V4021","V4022","V4024","V4025","V4026","V4027","V4028","V4029","V4032","V4033","V40331","V403311","V403312","V40332","V403321","V403322","V40333","V403331","V4034","V40341","V403411","V403412","V40342","V403421","V403422","V4039","V4039C","V4040","V40401","V40402","V40403","V4041","V4043","V40431","V4044","V4045","V4046","V4047","V4048","V4049","V4050","V40501","V405011","V405012","V40502","V405021","V405022","V40503","V405031","V4051","V40511","V405111","V405112","V40512","V405121","V405122","V4056","V4056C","V4057","V4058","V40581","V405811","V405812","V40582","V405821","V405822","V40583","V405831","V40584","V4059","V40591","V405911","V405912","V40592","V405921","V405922","V4062","V4062C","V4063","V4063A","V4064","V4064A","V4071","V4072","V4072A","V4073","V4074","V4074A","V4075A","V4075A1","V4076","V40761","V40762","V40763","V4077","V4078","V4078A","V4082","VD2002","VD2003","VD2004","VD3004","VD3005","VD3006","VD4001","VD4002","VD4003","VD4004","VD4004A","VD4005","VD4007","VD4008","VD4009","VD4010","VD4011","VD4012","VD4013","VD4014","VD4015","VD4016","VD4017","VD4018","VD4019","VD4020","VD4023","VD4030","VD4031","VD4032","VD4033","VD4034","VD4035","VD4036","VD4037",
]

In [48]:
PNADc.head()

,Ano,Trimestre,UF,Capital,RM_RIDE,UPA,Estrato,V1008,V1014,V1016,...,VD4020,VD4023,VD4030,VD4031,VD4032,VD4033,VD4034,VD4035,VD4036,VD4037
0,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,00001500,.,NaN,040,.,.,.,040,3,3
1,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,NaN,.,NaN,.,.,.,.,.,NaN,NaN
2,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,NaN,.,2,.,.,.,.,.,NaN,NaN
3,2020,1,11,11,NaN,110000016,1110011,01,07,5,...,NaN,.,NaN,.,.,.,.,.,NaN,NaN
4,2020,1,11,11,NaN,110000016,1110011,03,07,5,...,NaN,.,4,.,.,.,.,.,NaN,NaN

In [49]:
#Alterando os valores da coluna sexo 
PNADc['V2007'] = PNADc['V2007'].replace(['1'], 'Homem')
PNADc['V2007'] = PNADc['V2007'].replace(['2'], 'Mulher')

In [50]:
PNADc['V2007']

0         Mulher
1         Mulher
2         Mulher
3          Homem
4          Homem
           ...
487932    Mulher
487933    Mulher
487934    Mulher
487935     Homem
487936     Homem
Name: V2007, Length: 487937, dtype: object

In [51]:
#Atualizando os nomes das colunas. Ex. onde era 'V2007 para Sexo'
PNADc.columns =["Ano","Trimestre","UF","Capital","RM_RIDE","UPA","Estrato","V1008","V1014","V1016","V1022","V1023","V1027","V1028","V1029","posest","NÃºmero de pessoas no domicÃ­lio","V2003","V2005","Sexo","Dia de nascimento","MÃªs de nascimento","Ano de nascimento","Idade do morador na data de referÃªncia","V2010","V3001","V3002","V3002A","V3003","V3003A","V3004","V3005","V3005A","V3006","V3006A","V3007","V3008","V3009","V3009A","V3010","V3011","V3011A","V3012","V3013","V3013A","V3013B","V3014","V4001","V4002","V4003","V4004","V4005","V4006","V4006A","V4007","V4008","V40081","V40082","V40083","V4009","V4010","V4012","V40121","V4013","V40132","V40132A","V4014","V4015","V40151","V401511","V401512","V4016","V40161","V40162","V40163","V4017","V40171","V401711","V4018","V40181","V40182","V40183","V4019","V4020","V4021","V4022","V4024","V4025","V4026","V4027","V4028","V4029","V4032","V4033","V40331","V403311","V403312","V40332","V403321","V403322","V40333","V403331","V4034","V40341","V403411","V403412","V40342","V403421","V403422","V4039","V4039C","V4040","V40401","V40402","V40403","V4041","V4043","V40431","V4044","V4045","V4046","V4047","V4048","V4049","V4050","V40501","V405011","V405012","V40502","V405021","V405022","V40503","V405031","V4051","V40511","V405111","V405112","V40512","V405121","V405122","V4056","V4056C","V4057","V4058","V40581","V405811","V405812","V40582","V405821","V405822","V40583","V405831","V40584","V4059","V40591","V405911","V405912","V40592","V405921","V405922","V4062","V4062C","V4063","V4063A","V4064","V4064A","V4071","V4072","V4072A","V4073","V4074","V4074A","V4075A","V4075A1","V4076","V40761","V40762","V40763","V4077","V4078","V4078A","V4082","VD2002","VD2003","VD2004","VD3004","VD3005","VD3006","VD4001","VD4002","VD4003","VD4004","VD4004A","VD4005","VD4007","VD4008","VD4009","VD4010","VD4011","VD4012","VD4013","VD4014","VD4015","VD4016","VD4017","VD4018","VD4019","VD4020","VD4023","VD4030","VD4031","VD4032","VD4033","VD4034","VD4035","VD4036","VD4037",
]

In [52]:
# ajustando pois pelo dicionÃ¡rio 99 significa que nÃ£o foi informado
PNADc['Dia de nascimento'] = PNADc['Dia de nascimento'].replace(['99'], 'NaN')
PNADc['MÃªs de nascimento'] = PNADc['MÃªs de nascimento'].replace(['99'], 'NaN')
PNADc['Ano de nascimento'] = PNADc['Ano de nascimento'].replace(['9999'], 'NaN')

In [53]:
PNADc['V2010'] = PNADc['V2010'].replace(['1'], 'Branca')
PNADc['V2010'] = PNADc['V2010'].replace(['2'], 'Preta')
PNADc['V2010'] = PNADc['V2010'].replace(['3'], 'Amarela')
PNADc['V2010'] = PNADc['V2010'].replace(['4'], 'Parda')
PNADc['V2010'] = PNADc['V2010'].replace(['5'], 'IndÃ­gena')
PNADc['V2010'] = PNADc['V2010'].replace(['9'], 'Ignorado')

In [54]:
PNADc['V2010']

0          Parda
1          Parda
2          Parda
3          Parda
4         Branca
           ...
487932    Branca
487933    Branca
487934     Parda
487935     Parda
487936     Parda
Name: V2010, Length: 487937, dtype: object

In [55]:
#atualizo v2010 para cor e raÃ§a
PNADc.columns =["Ano","Trimestre","UF","Capital","RM_RIDE","UPA","Estrato","V1008","V1014","V1016","V1022","V1023","V1027","V1028","V1029","posest","NÃºmero de pessoas no domicÃ­lio","V2003","V2005","Sexo","Dia de nascimento","MÃªs de nascimento","Ano de nascimento","Idade do morador na data de referÃªncia","Cor ou raÃ§a","V3001","V3002","V3002A","V3003","V3003A","V3004","V3005","V3005A","V3006","V3006A","V3007","V3008","V3009","V3009A","V3010","V3011","V3011A","V3012","V3013","V3013A","V3013B","V3014","V4001","V4002","V4003","V4004","V4005","V4006","V4006A","V4007","V4008","V40081","V40082","V40083","V4009","V4010","V4012","V40121","V4013","V40132","V40132A","V4014","V4015","V40151","V401511","V401512","V4016","V40161","V40162","V40163","V4017","V40171","V401711","V4018","V40181","V40182","V40183","V4019","V4020","V4021","V4022","V4024","V4025","V4026","V4027","V4028","V4029","V4032","V4033","V40331","V403311","V403312","V40332","V403321","V403322","V40333","V403331","V4034","V40341","V403411","V403412","V40342","V403421","V403422","V4039","V4039C","V4040","V40401","V40402","V40403","V4041","V4043","V40431","V4044","V4045","V4046","V4047","V4048","V4049","V4050","V40501","V405011","V405012","V40502","V405021","V405022","V40503","V405031","V4051","V40511","V405111","V405112","V40512","V405121","V405122","V4056","V4056C","V4057","V4058","V40581","V405811","V405812","V40582","V405821","V405822","V40583","V405831","V40584","V4059","V40591","V405911","V405912","V40592","V405921","V405922","V4062","V4062C","V4063","V4063A","V4064","V4064A","V4071","V4072","V4072A","V4073","V4074","V4074A","V4075A","V4075A1","V4076","V40761","V40762","V40763","V4077","V4078","V4078A","V4082","VD2002","VD2003","VD2004","VD3004","VD3005","VD3006","VD4001","VD4002","VD4003","VD4004","VD4004A","VD4005","VD4007","VD4008","VD4009","VD4010","VD4011","VD4012","VD4013","VD4014","VD4015","VD4016","VD4017","VD4018","VD4019","VD4020","VD4023","VD4030","VD4031","VD4032","VD4033","VD4034","VD4035","VD4036","VD4037",
]

In [40]:
PNADc['Cor ou raÃ§a']

0          Parda
1          Parda
2          Parda
3          Parda
4         Branca
           ...
487932    Branca
487933    Branca
487934     Parda
487935     Parda
487936     Parda
Name: Cor ou raÃ§a, Length: 487937, dtype: object